CREATE TABLE IF NOT EXISTS `payment_reminders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(20) NOT NULL,
  `folio` VARCHAR(50) NULL,
  `cuenta` VARCHAR(50) NOT NULL,
  `due_date` DATE NOT NULL,
  `next_due_date` DATE NULL,
  `scheduled_for` DATETIME NOT NULL,
  `reminder_type` VARCHAR(50) NOT NULL,
  `template_name` VARCHAR(120) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'scheduled',
  `receipt_status` VARCHAR(40) NOT NULL DEFAULT 'none',
  `receipt_id` INT NULL,
  `saldo_snapshot` DECIMAL(13,2) NULL,
  `monto_minimo_snapshot` DECIMAL(13,2) NULL,
  `bridge_found` TINYINT(1) NOT NULL DEFAULT 0,
  `bridge_snapshot_hash` VARCHAR(64) NULL,
  `meta_message_id` VARCHAR(120) NULL,
  `error_code` VARCHAR(80) NULL,
  `error_message_sanitized` VARCHAR(255) NULL,
  `dry_run` TINYINT(1) NOT NULL DEFAULT 0,
  `sent_at` DATETIME NULL,
  `paused_at` DATETIME NULL,
  `reactivated_at` DATETIME NULL,
  `cancelled_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payment_reminders_account_due_type` (`cuenta`, `due_date`, `reminder_type`),
  KEY `idx_payment_reminders_account_due_type` (`cuenta`, `due_date`, `reminder_type`),
  KEY `idx_payment_reminders_status_scheduled` (`status`, `scheduled_for`),
  KEY `idx_payment_reminders_phone` (`phone`),
  KEY `idx_payment_reminders_folio` (`folio`),
  KEY `idx_payment_reminders_cuenta` (`cuenta`),
  KEY `idx_payment_reminders_receipt_status` (`receipt_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
