TIPO_VIALIDAD = {
    "1": "Ampliación",
    "2": "Andador",
    "3": "Avenida",
    "4": "Boulevard",
    "5": "Calle",
    "6": "Callejón",
    "7": "Calzada",
    "8": "Cerrada",
    "9": "Circuito",
    "10": "Circunvalación",
    "11": "Continuación",
    "12": "Corredor",
    "13": "Diagonal",
    "14": "Eje Vial",
    "15": "Pasaje",
    "16": "Peatonal",
    "17": "Periférico",
    "18": "Privada",
    "19": "Prolongación",
    "20": "Retorno",
    "21": "Viaducto",
}