from enum import Enum


class ChatState(str, Enum):
    ESPERA = "ESPERA"
    INICIO = "INICIO"

    CAMBIAR_FOLIO = "CAMBIAR_FOLIO"
    MENU_AYUDA = "MENU_AYUDA"

    CONFIRMAR_FOLIO = "CONFIRMAR_FOLIO"
    CONFIRMAR_NOMBRE = "CONFIRMAR_NOMBRE"
    CONFIRMAR_DOMICILIO = "CONFIRMAR_DOMICILIO"
    CONFIRMAR_FECHA = "CONFIRMAR_FECHA"
    CONFIRMAR_PRODUCTO = "CONFIRMAR_PRODUCTO"
    CONFIRMAR_ESTADO_PRODUCTO = "CONFIRMAR_ESTADO_PRODUCTO"
    CONFIRMAR_COMPONENTES = "CONFIRMAR_COMPONENTES"
    CONFIRMAR_PAGO_INICIAL = "CONFIRMAR_PAGO_INICIAL"

    INCONSISTENCIA = "INCONSISTENCIA"
    FUERA_DE_FLUJO = "FUERA_DE_FLUJO"
    ESCRIBIR_INCONSISTENCIA = "ESCRIBIR_INCONSISTENCIA"

    COMPONENTES_FALTANTES = "COMPONENTES_FALTANTES"
    COMPONENTES_CONFIRMAR_FALTANTES = "COMPONENTES_CONFIRMAR_FALTANTES"

    INFO_PAGOS = "INFO_PAGOS"
    INFO_METODOS_PAGO = "INFO_METODOS_PAGO"
    INFO_PLAN_3_MESES = "INFO_PLAN_3_MESES"
    INFO_PLAN_6_MESES = "INFO_PLAN_6_MESES"
    INFO_OTROS_PLANES = "INFO_OTROS_PLANES"
    INFO_BENEFICIOS = "INFO_BENEFICIOS"
    INFO_BENEFICIOS2 = "INFO_BENEFICIOS2"
    RECORDATORIO_1H = "RECORDATORIO_1H"
    RECORDATORIO_2H = "RECORDATORIO_2H"

    FINALIZADO = "FINALIZADO"

    ACLARACION = "ACLARACION"
    RECORDATORIO = "RECORDATORIO"
    LLAMADA = "LLAMADA"
