from enum import Enum


class ChatState(str, Enum):
    ESPERA = "ESPERA"
    INICIO = "INICIO"

    CONFIRMAR_NOMBRE = "CONFIRMAR_NOMBRE"
    CONFIRMAR_DOMICILIO = "CONFIRMAR_DOMICILIO"
    CONFIRMAR_FECHA = "CONFIRMAR_FECHA"
    CONFIRMAR_PRODUCTO = "CONFIRMAR_PRODUCTO"
    CONFIRMAR_COMPONENTES = "CONFIRMAR_COMPONENTES"
    CONFIRMAR_PAGO_INICIAL = "CONFIRMAR_PAGO_INICIAL"

    INCONSISTENCIA = "INCONSISTENCIA"
    FUERA_DE_FLUJO = "FUERA_DE_FLUJO"

    INFO_PAGOS = "INFO_PAGOS"
    INFO_BANCOS = "INFO_BANCOS"
    PLAN_3_MESES = "PLAN_3_MESES"
    INFO_PLANES = "INFO_PLANES"
    BENEFICIOS = "BENEFICIOS"

    FINALIZADO = "FINALIZADO"

    ACLARACION = "ACLARACION"
    RECORDATORIO = "RECORDATORIO"
    LLAMADA = "LLAMADA"
