from enum import Enum


class ChatState(str, Enum):
    ESPERA = "ESPERA"
    INICIO = "INICIO"

    CONFIRMAR_NOMBRE = "CONFIRMAR_NOMBRE"
    CONFIRMAR_DOMICILIO = "CONFIRMAR_DOMICILIO"
    CONFIRMAR_FECHA = "CONFIRMAR_FECHA"
    CONFIRMAR_PRODUCTO = "CONFIRMAR_PRODUCTO"
    CONFIRMAR_COMPONENTES = "CONFIRMAR_COMPONENTES"
    CONFIRMAR_PAGO_INICIAL = "CONFIRMAR_PAGO_INICIAL"

    INCONSISTENCIA = "INCONSISTENCIA"
    FUERA_DE_FLUJO = "FUERA_DE_FLUJO"

    COMPONENTES_FALTANTES = "COMPONENTES_FALTANTES"
    COMPONENTES_CONFIRMAR_FALTANTES = "COMPONENTES_CONFIRMAR_FALTANTES"

    INFO_PAGOS = "INFO_PAGOS"
    INFO_METODOS_PAGO = "INFO_METODOS_PAGO"
    INFO_PLAN_3_MESES = "INFO_PLAN_3_MESES"
    INFO_PLAN_6_MESES = "INFO_PLAN_6_MESES"
    INFO_OTROS_PLANES = "INFO_OTROS_PLANES"
    INFO_BENEFICIOS = "INFO_BENEFICIOS"

    FINALIZADO = "FINALIZADO"

    ACLARACION = "ACLARACION"
    RECORDATORIO = "RECORDATORIO"
    LLAMADA = "LLAMADA"
